name: "Release WIP to Workshop"
on:
  release:
    types: [published]

jobs:
  build_wip:
    runs-on: windows-latest
    if: "github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v1
      - name: Set VERSION env
        run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
      # Build with Mikero
      - name: Build with Mikero
        run: |
          "C:\Core_WIP.bat"
      # Upload to Steam Workshop
      - uses: arma-actions/workshop-upload@v1
        with:
          appId: "107410" # default
          itemId: "2837988642" # Id of item to update
          contentPath: 'D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CGQC - Core - WIP'
          changelog: "${{ github.event.release.body }}"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
