name: 'Release WIP to Workshop'

on:
  release.prerelease:

jobs:
  build_addon:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    # Upload to Steam Workshop
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '2837988642' # Id of item to update
        contentPath: 'D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CGQC - Core - WIP'
        changelog: 'Content of change notes'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}