name: "Release WIP to Workshop"
on:
  release:
    types: [published]

jobs:
  build_wip:
    runs-on: windows-latest
    if: "github.event.release.prerelease"
    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v2
      # Build code with Mikero
      - name: Build with Mikero
        run: |
          Core_WIP.bat
      # Upload on workshop
      - name: steam-workshop-upload
        uses: weilbyte/steam-workshop-upload@v1
        with:
          appid: 107410 # Game's Steam App ID
          itemid: 2837988642 # Your mod's Steam Workshop ID
          path: "release" # Path to your mod's folder from repository root
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
