name: "Release WIP to Workshop"
on:
  release:
    types: [published]

jobs:
  build_wip:
    runs-on: windows-latest
    if: "github.event.release.prerelease"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Upload mod
      uses: gruppe-adler/action-release-to-steam-ws@v1-beta
      with:
        file_id: 2837988642
        username: "${{ secrets.STEAM_USERNAME }}"
        password: "${{ secrets.STEAM_PASSWORD }}"
        path: "D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CGQC - Core - WIP"
        name: "CGQC - Core - WIP"
        change_notes_title: "${{ github.event.release.name }}"
        change_notes: "${{ github.event.release.body }}"
