name: "Release Full to Workshop"
on:
  release:
    types: [published]

jobs:
  build_addon:
    runs-on: windows-latest
    if: "!github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v1
      - name: Set VERSION env
        run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
      # Build with Mikero
      - name: Build with Mikero
        run: |
          C:\Core_Release.bat
      # Upload to Steam Workshop
      - uses: arma-actions/workshop-upload@v1
        with:
          appId: "107410" # default
          itemId: "Core_Release.bat" # Id of item to update
          contentPath: 'P:\Max_dev\Mods\release\@CGQC'
          changelog: "${{ github.event.release.body }}"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
